config:
  #link to the graphite's render script
  render: http://graphite:8080/render
  #if graphite is protected by http simple auth you can provide username/password
  username: admin
  password: supersecretpassword
  #graphite query interval in seconds
  interval: 60 #data fetch interval in seconds
  #(optional, defaults to ./plumbago.pid) where to write plumbago server's pid number
  pidfile: pl.pid
  logging:
    debug: no
    #(optional, defaults to plumbago.log) where to write the log file (all log levels)
    file: pl.log

agents:
  - name: hipchat
    class: plumbago.agents.HipchatAgent
    api_key: HipChat_API_KEY
    room_id: HipChat_ROOM_ID
    from: plumbago
    format: text
    notify: 1
    error_color: red
    normal_color: green
    #template is used to format the message, parameters:
    #   $name: alert name
    #   $target: alert target
    #   $ts: alert timestamp
    #   $threshold: alert threshold
    #   $value: alert value
    normal_template: "OK $name: $target is back to normal $value < $threshold"
    error_template: "ERROR $name: $target is above threshold $value >= $threshold @demian"

alerts:
  example_alert:
    #graphite target
    target: diffSeries(servers.DBMaster.memory.MemFree,servers.DBMaster.memory.MemTotal)
    #limit value before alerting
    threshold: 17494441984
    #(optional, defaults to no) if active it will check if the value goes under the threshold instead of over it
    reverse: no
    #(optional, defaults to yes) whether the alert will be checked or not
    enabled: yes
    #seconds to wait between alarms
    diff: 600
    #list of agents
    agents:
      - hipchat