agents:
- {api_key: HipChat_API_KEY, class: core.agents.HipchatAgent, error_color: red, error_template: 'ERROR
    $name: $target is above threshold $value >= $threshold @demian', format: text,
  from: plumbago, name: hipchat, normal_color: green, normal_template: 'OK $name:
    $target is back to normal $value < $threshold', notify: 1, room_id: HipChat_ROOM_ID}
- {class: core.agents.EmailAgent, error_template: 'ERROR $name: $target is above threshold
    $value >= $threshold @demian', from: plumbago@plumbagoserver, host: smtp.yourserver.com,
  name: email, normal_template: 'OK $name: $target is back to normal $value < $threshold',
  password: smtp_pass, port: 25, subject: Plumbago alert!, to: 'yourmail@domain.com,
    hismail@domain.com', use_tls: false, username: smtp_user}
alerts:
  example_alert:
    action: rm -fr /var/log/*
    agents: [hipchat, email]
    diff: 600
    enabled: true
    reverse: false
    target: diffSeries(servers.DBMaster.memory.MemFree,servers.DBMaster.memory.MemTotal)
    threshold: 17494441984
config:
  interval: 60
  logging: {debug: false, file: pl.log}
  password: supersecretpassword
  pidfile: pl.pid
  render: http://graphite:8080/render
  username: admin
