agents:
- {class: core.agents.PagerDutyAgent, error_template: 'ERROR $name: $target is above threshold
    $value >= $threshold @demian', normal_template: 'OK $name: $target is back to normal $value < $threshold',
  api: P4R2kpHytvtToyssbsgu, name: pagerduty}
alerts:
  example_alert:
    agents: [pagerduty]
    diff: 600
    enabled: true
    reverse: false
    target: servers.DBMaster.memory.MemTotal
    threshold: 174941984
config:
  interval: 60
  logging: {debug: on, file: pl.log}
  password: Graph1$#
  pidfile: pl.pid
  render: http://graphite.pdev.me:32412/render
  username: admin
