#!/usr/bin/env python

import logging
import signal
import os
import time
import json
import sys
import yaml

from core import Plumbago


__author__ = 'uzix & dembar'

log = logging.getLogger()


class colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    GRAY = '\033[90m'
    YELLOW = '\033[93m'
    DEF = '\033[0m'

    def disable(self):
        self.GREEN = ''
        self.RED = ''
        self.GRAY = ''
        self.YELLOW = ''
        self.DEF = ''


def createDaemon():
    try:
        pid = os.fork()
    except OSError, e:
        raise Exception, "%s [%d]" % (e.strerror, e.errno)

    if pid == 0:
        os.setsid()
        try:
            pid = os.fork()
        except OSError, e:
            raise Exception, "%s [%d]" % (e.strerror, e.errno)

        if pid != 0:
            os._exit(0)
    else:
        os._exit(0)

    return


def getPlumbagoPid(pidFile):
    try:
        with open(pidFile, 'r') as _pidFile:
            return int(_pidFile.readline())
    except IOError:
        print "Could not open Plumbago pidfile", pidFile
        exit(1)


def definePidFile(config):
    try:
        return config['config']['pidfile']
    except KeyError:
        return '%s/plumbago.pid' % sys.path[0]


def defineLogFile(config):
    try:
        return config['config']['logging']['file']
    except KeyError:
        return '%s/plumbago.log' % sys.path[0]


def getAlertStatus(alertName):
    time.sleep(1)
    try:
        with open('/tmp/plumbago.status', 'r') as statusfile:
            alerts = json.load(statusfile)
    except IOError as ex:
        log.error('[Plumbago] Failed to load alerts status. Error: %s', ex)
        return

    if alertName.lower() == 'all':
        for alert in alerts:
            if alert['status'] == 0:
                print '%s: %sOK%s' % (alert['name'], colors.GREEN, colors.DEF)
            elif alert['status'] == 1:
                print '%s: %sERROR%s' % (alert['name'], colors.RED, colors.DEF)
            elif alert['status'] == 2:
                print '%s: %sDISABLED%s' % (alert['name'], colors.GRAY, colors.DEF)
            elif alert['status'] == 3:
                print '%s: %sUNKNOWN%s' % (alert['name'], colors.YELLOW, colors.DEF)

    elif alertName.lower() == 'error':
        for alert in alerts:
            if alert['status'] == 1:
                print '%s: %sERROR%s' % (alert['name'], colors.RED, colors.DEF)

    elif alertName.lower() == 'disabled':
        for alert in alerts:
            if alert['status'] == 2:
                print '%s: %sDISABLED%s' % (alert['name'], colors.GRAY, colors.DEF)

    elif alertName.lower == 'unknown':
        for alert in alerts:
            if alert['status'] == 3:
                print '%s: %sUNKNOWN%s' % (alert['name'], colors.YELLOW, colors.DEF)
    else:
        found = False
        for alert in alerts:
            if alert['name'].lower() == alertName.lower():
                found = True
                print "\nName:", alert['name']
                print "Target:", alert['target']

                try:
                    print "Enabled:", alert['enabled']
                except KeyError:
                    print "Enabled?: True"

                try:
                    print "Action:", alert['action']
                except KeyError:
                    print "Action?: None"

                try:
                    print "Reverse?:", alert['reverse']
                except KeyError:
                    print "Reverse?: False"

                print "Value:", str(alert['value'])
                print "Threshold:", str(alert['threshold'])
                print "Cycles:", str(alert['cycles'])

                if alert['status'] == 0:
                    print 'Status: %sOK%s' % (colors.GREEN, colors.DEF)
                elif alert['status'] == 1:
                    print 'Status: %sERROR%s' % (colors.RED, colors.DEF)
                elif alert['status'] == 2:
                    print 'Status: %sDISABLED%s' % (colors.GRAY, colors.DEF)
                elif alert['status'] == 3:
                    print 'Status: %sUNKNOWN%s\n' % (colors.YELLOW, colors.DEF)

                try:
                    print "Comment:", alert['comment']
                except KeyError:
                    print "Comment: None"

                print
                break
        if not found:
            print "\nNo alert exists with that name. Try -t all to see the complete list of alerts\n"
    os.remove('/tmp/plumbago.status')


def binaryChange(enable, disable, reverse, config, configFile):
    pidFile = config['config']['pidfile']
    logFile = config['config']['logging']['file']

    try:
        with open(configFile, 'r') as oldConfig:
            config = yaml.load(oldConfig)
    except IOError:
        print 'Could not open config file', configFile
        return

    pending = True
    while pending:
        if enable:
            alertName = enable
            action = 'enabled'
            new_status = True
            enable = False
            if not (disable or reverse):
                pending = False

        elif disable:
            alertName = disable
            action = 'enabled'
            new_status = False
            disable = False
            if not (enable or reverse):
                pending = False

        elif reverse:
            alertName = reverse
            action = 'reverse'
            try:
                if config['alerts'][alertName]['reverse']:
                    new_status = False
                else:
                    new_status = True
            except KeyError:
                new_status = True
            reverse = False
            if not (enable or disable):
                pending = False

        if alertName.lower() == 'all':
            for alert in config['alerts']:
                if reverse:
                    try:
                        if config['alerts'][alert]['reverse']:
                            new_status = False
                        else:
                            new_status = True
                    except KeyError:
                        new_status = True

                try:
                    config['alerts'][alert][action] = new_status
                except KeyError:
                    continue
        else:
            try:
                config['alerts'][alertName][action] = new_status
            except KeyError:
                print "\nNo alert exists with that name. Try -t all to see the complete list of alerts\n"
                return

    try:
        with open(configFile, 'w') as newConfig:
            yaml.dump(config, newConfig)
        log.info('[Plumbago] Enabled', alertName)
        config['config']['pidfile'] = pidFile
        config['config']['logging']['file'] = logFile
        if serverRunning(config):
            reloadConfig(config['config']['pidfile'])
    except Exception as ex:
        log.error('[Plumbago] Could not save new config. Error: %s', ex)


def paramChange(agent, threshold, target, diff, cycles, action, comment, config, configFile):
    pidFile = config['config']['pidfile']
    logFile = config['config']['logging']['file']

    try:
        with open(configFile, 'r') as oldConfig:
            config = yaml.load(oldConfig)
    except IOError:
        print 'Could not open config file', configFile
        return

    pending = True
    while pending:
        if agent:
            alertName = agent[0]
            field = 'agents'
            new_value = agent[1].split(',')
            agent = False
            if not (threshold or target or diff or cycles or action or comment):
                pending = False

        elif threshold:
            alertName = threshold[0]
            field = 'threshold'
            new_value = float(threshold[1])
            threshold = False
            if not (agent or target or diff or cycles or action or comment):
                pending = False

        elif target:
            alertName = target[0]
            field = 'target'
            new_value = target[1]
            target = False
            if not (agent or threshold or diff or cycles or action or comment):
                pending = False

        elif diff:
            alertName = diff[0]
            field = 'diff'
            new_value = int(diff[1])
            diff = False
            if not (agent or threshold or target or cycles or action or comment):
                pending = False

        elif cycles:
            alertName = cycles[0]
            field = 'error_cycles'
            new_value = int(cycles[1])
            cycles = False
            if not (agent or threshold or target or diff or action or comment):
                pending = False

        elif action:
            alertName = action[0]
            field = 'action'
            if str(action[1].lower()) == 'false' or str(action[1].lower()) == 'none':
                new_value = False
            else:
                new_value = action[1]
            action = False
            if not (agent or threshold or target or diff or cycles or comment):
                pending = False

        elif comment:
            alertName = comment[0]
            field = 'comment'
            new_value = comment[1]
            comment = False
            if not (agent or threshold or target or diff or cycles or action):
                pending = False

        elif alertName.lower() == 'all' and not (threshold or target):
            for alert in config['alerts']:
                try:
                    config['alerts'][alert][field] = new_value
                except KeyError:
                    continue

        try:
            config['alerts'][alertName][field] = new_value
        except KeyError:
            print "\nNo alert exists with that name. Try -t all to see the complete list of alerts\n"
            return

    try:
        with open(configFile, 'w') as newConfig:
            yaml.dump(config, newConfig)
        log.info('[Plumbago] Enabled', alertName)
        config['config']['pidfile'] = pidFile
        config['config']['logging']['file'] = logFile
        if serverRunning(config):
            reloadConfig(config['config']['pidfile'])
    except Exception as ex:
        print "\nFailed to save new configuration"
        log.error('[Plumbago] Could not save new config. Error: %s', ex)


def startServer(config, configFileOpt):
    print "Starting Plumbago server..."
    createDaemon()

    with open(config['config']['pidfile'], 'w') as pidfile:
        pidfile.write(str(os.getpid()))

    server = Plumbago(config)
    log.info('[Plumbago] Plumbago server started')

    def handler(signum, frame):
        if signum == signal.SIGUSR1:
            try:
                with open(configFileOpt, 'r') as configFile:
                    config = yaml.load(configFile)
            except IOError as ex:
                print "Could not load configuration file", configFileOpt
                log.error('[Plumbago] Could not load configuration file %s. Error: %s', configFileOpt, ex)
                return
            server.configure(config)
        elif signum == signal.SIGUSR2:
            server.dump_status()
        elif signum == signal.SIGTERM:
            log.info('[Plumbago] Received SIGTERM gracefully stopping in next runloop')
            server._running = False

    signal.signal(signal.SIGTERM, handler)
    signal.signal(signal.SIGUSR1, handler)
    signal.signal(signal.SIGUSR2, handler)

    server.run()

    os.remove(config['config']['pidfile'])
    return


def reloadConfig(pidFile):
    try:
        os.kill(getPlumbagoPid(pidFile), signal.SIGUSR1)
        print "Reloading Plumbago configuration..."
        log.debug('[Plumbago] Sent USR1 signal')
    except OSError:
        print "Plumbago server not running!"
        exit(1)


def terminateServer(pidFile):
    try:
        os.kill(getPlumbagoPid(pidFile), signal.SIGTERM)
        print "Killing Plumbago server..."
        log.debug('[Plumbago] Sent TERM signal')
    except OSError:
        print "Plumbago server not running!"
        exit(1)


def serverRunning(config):
    if os.path.exists(config['config']['pidfile']):
        try:
            os.kill(getPlumbagoPid(config['config']['pidfile']), 0)
            return True
        except OSError:
            print "Removing bogus pid file..."
            os.remove(config['config']['pidfile'])
            log.debug('[Plumbago] Removed bogus pid file')
            return False


def main():
    from argparse import ArgumentParser

    parser = ArgumentParser(prog='plumbago')
    server_group = parser.add_argument_group('Server')
    file_group = parser.add_argument_group('Files', 'Define where core files are or go')
    alert_group = parser.add_argument_group('Alerts', 'See and modify alerts')

    server_group.add_argument('--server', dest='server', action='store_true', default=False,
                              help='Run Plumbago Server')
    server_group.add_argument('--reload', dest='reload', action='store_true', default=False,
                              help="Reload Plumbago configuration")
    server_group.add_argument('--kill', dest='kill', action='store_true', default=False,
                              help='Kill Plumbago server')
    server_group.add_argument('--web', dest='web', action='store_true', default=False,
                              help='Start web server')

    file_group.add_argument('--config', dest='config', default='%s/config.yaml' % sys.path[0],
                            help='Plumbago config file', nargs=1, metavar='CONFIG_FILE')
    file_group.add_argument('--log-file', dest='log', nargs=1, metavar='LOG_FILE',
                            help='Plumbago log file')
    file_group.add_argument('--pid-file', dest='pid', nargs=1, metavar='PID_FILE',
                            help='Plumbago pid file')

    alert_group.add_argument('-a', '--agent', dest='agent', nargs=2, metavar=('ALERT_NAME', 'AGENT'),
                             help='Change notification agent for an alert [alert_name|all|error]')
    alert_group.add_argument('-c', '--cycles', dest='cycles', nargs=2, metavar=('ALERT_NAME', 'INT'),
                             help='Modify alert cycles before alerting [alert_name|all]')
    alert_group.add_argument('-d', '--disable', dest='disable', metavar='ALERT_NAME',
                             help='Disable alert [alert_name|all]')
    alert_group.add_argument('-e', '--enable', dest='enable', metavar='ALERT_NAME',
                             help='Enable alert [alert_name|all]')
    alert_group.add_argument('-f', '--diff', dest='diff', nargs=2, metavar=('ALERT_NAME', 'SECONDS'),
                             help='Modify time between alerts [alert_name|all]')
    alert_group.add_argument('-l', '--threshold', dest='threshold', nargs=2, metavar=('ALERT_NAME', 'THRESHOLD'),
                             help='Modify alert threshold')
    alert_group.add_argument('-m', '--comment', dest='comment', nargs=2, metavar=('ALERT_NAME', 'COMMENT'),
                             help='Modify alert comment')
    alert_group.add_argument('-r', '--reverse', dest='reverse', metavar='ALERT_NAME',
                             help='Reverse alert check [alert_name|error]')
    alert_group.add_argument('-s', '--status', dest='status', metavar='ALERT_NAME',
                             help='Show alerts statuses [alert_name|all|error|disabled|unknown]')
    alert_group.add_argument('-t', '--target', dest='target', nargs=2, metavar=('ALERT_NAME', 'TARGET'),
                             help='Modify alert target')
    alert_group.add_argument('-x', '--action', dest='action', nargs=2, metavar=('ALERT_NAME', 'ACTION'),
                             help='Modify alert action')

    options = parser.parse_args()

    try:
        with open(options.config, 'r') as configFile:
            config = yaml.load(configFile)
    except Exception as ex:
        print "Could not load configuration file", options.config
        log.error('Could not load configuration file %s. Error: %s', options.config, ex)
        return
    log.debug('[Plumbago] Config file is:', options.config)

    if not options.pid:
        config['config']['pidfile'] = definePidFile(config)
    else:
        config['config']['pidfile'] = options.pid
    log.debug('[Plumbago] Pid File is:', config['config']['pidfile'])

    if not options.log:
        config['config']['logging']['file'] = defineLogFile(config)
    else:
        config['config']['logging']['file'] = options.log
    log.debug('[Plumbago] Log File is:', config['config']['logging']['file'])


    if options.server:
        if not serverRunning(config):
            startServer(config, options.config)
        else:
            print "Plumbago server already running!"

    elif options.enable or options.disable or options.reverse:
        binaryChange(options.enable, options.disable, options.reverse, config, options.config)

    elif options.agent or options.threshold or options.target or options.diff or options.cycles or options.comment or options.action:
        paramChange(options.agent, options.threshold, options.target, options.diff, options.cycles, options.action, options.comment, config, options.config)

    elif options.kill:
        if serverRunning(config):
            terminateServer(config['config']['pidfile'])
        else:
            print "Plumbago server not running!"

    elif options.reload:
        if serverRunning(config):
            pidFile = config['config']['pidfile']
            logFile = config['config']['logging']['file']
            reloadConfig(config['config']['pidfile'])
            config['config']['pidfile'] = pidFile
            config['config']['logging']['file'] = logFile
        else:
            print "Plumbago server not running!"

    elif options.status:
        if serverRunning(config):
            os.kill(getPlumbagoPid(config['config']['pidfile']), signal.SIGUSR2)
            getAlertStatus(options.status)
        else:
            print "Plumbago server not running!"

    else:
        print "\nNothing to do..."
        parser.print_usage()
        return


if __name__ == "__main__":
    main()